version: "3"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      SUBDOMAINS: /run/secrets/duckdns_domain
      TOKEN: /run/secrets/duckdns_token
      LOG_FILE: "true"
    volumes:
      - /path/to/appdata/config:/config #optional
    labels:
      io.containers.autoupdate: "registry"
    secrets:
      - duckdns_token
    
  reverse-proxy:
    #The original v2 Traefik docker image
    image: docker.io/traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    #Enable Web-UI and listen to docker/podman socket
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"    # HTTP 
      - "443:443"  # HTTPS
      - "8080:8080"# Web-UI (enabled by --api.insecure=true)
    volumes:
      #Socket listen for docker/podman events (traefik labels)
      - /var/run/podman/podman.sock:/var/run/docker.sock:Z
    labels:
      io.containers.autoupdate: "registry"

secrets:
  duckdns_token:
    file: .secrets.d/duckdns_token.txt
  duckdns_domain:
    file: .secrets.d/duckdns_domain.txt

networks:
  
